### PR TITLE
add check for installation ipopt

### PR DESCRIPTION
**Pull request by jvanhoefer**
Currently it was not checked, if IpOpt is installed.

### CODE REVIEW

**Comment by yannikschaelte** [comment]
I think we should do this similarly for many optional dependencies (pyswarm, pymc3, ipopt, dlib, ...). Checking for availability like here when invoking the main class? As e.g. the IpoptOptimizer is imported into pypesto.optimize by default, catching on import submodule is currently not possible, so this way here would seem fine to me. Opinions? @FFroehlich @dweindl

**Comment by FFroehlich** [comment]
> I think we should do this similarly for many optional dependencies (pyswarm, pymc3, ipopt, dlib, ...). Checking for availability like here when invoking the main class? As e.g. the IpoptOptimizer is imported into pypesto.optimize by default, catching on import submodule is currently not possible, so this way here would seem fine to me. Opinions? @FFroehlich @dweindl

Looks good to me.

**Comment by dweindl** [comment]
Works for me. For this and similar examples, one could also postpone the import to the respective functions. This is the only place ipopt is actually used. No need to load all those libraries that are rarely used in combination...

**Comment by jvanhoefer** [comment]
This is also how it is done for all other optimizers except IpOpt...

**Comment by jvanhoefer** [comment]
This is also how it is done for all other optimizers except IpOpt...

**Comment by jvanhoefer** [comment]
Still agree, that we should do more specific error messages, if optional dependencies are used, see also e.g. #467

**Review by yannikschaelte — APPROVED** [review]

**Pull request merged**
