### PR TITLE
Log traceback in case of exceptions during optimizations

### LINKED ISSUE #1147: Uninformative `'hess'` in `OptimizerResult.message`
Sometimes optimization results have `'hess'` as `OptimizerResult.message` which is not all that helpful. I encountered it with FidesOptimizer, but I can't say it's specific to that.  Not completely sure where it's coming from, but my guess would be https://github.com/ICB-DCM/pyPESTO/blob/883138a63a8911e51884be9dff2028d374ad69f6/pypesto/optimize/optimizer.py#L1340

~~As a start, it would be good to change that line to include the type of exception and stack trace.~~ 

EDIT: No, it's not that line and including the stack traces would currently mess up the messages for non-finite starting points and others.

### PR DESCRIPTION
**Pull request by dweindl**
So far, with `minimize(..., OptimizeOptions(allow_failed_starts=True))`
only the exception message was stored/logged, which is not always sufficiently
informative (see #1147).

Now we log the full exception type / message / traceback.

Closes #1147

### CODE REVIEW

**Review by PaulJonasJost — APPROVED** [review]
Does this include the whole traceback now? might be quite long, but good to have for this anyways.

Not sure on policies we have on importing, but possibly nicer to have them as default import for the sake of better overview?

**Comment by dweindl** [comment]
> Does this include the whole traceback now? might be quite long, but good to have for this anyways.

Yes. One can always shorten it later. But previously this didn't contain sufficient information to debug anything.

> Not sure on policies we have on importing, but possibly nicer to have them as default import for the sake of better overview?

No clear policy. But if those modules are only required under exceptional circumstances, i would only import them under exceptional circumstances.
I would rather not go back to https://github.com/ICB-DCM/pyPESTO/issues/934

**Comment by dweindl** [comment]
Okay, this is not quite what we want. This messes up handling of cases like `RuntimeError: Encountered non-finite function inf value at initial point.`.

**Comment by dweindl** [comment]
> Okay, this is not quite what we want. This messes up handling of cases like `RuntimeError: Encountered non-finite function inf value at initial point.`.

Changed now. Leaving FidesOptimizer exception reporting as it was, just changing it for the non-caught exceptions. Only logging the full traceback, but keeping the result message short. Should be reasonable compromise.

@PaulJonasJost Please re-review.

**Pull request merged**
