### PR TITLE
Add importer for PySB-based PEtab problems

### LINKED ISSUE #436: PySB-PEtab importer
With https://github.com/ICB-DCM/AMICI/pull/1175, AMICI will be able to handle PySB-based PEtab problems. Would be great to support PySB then also in pyPESTO.

I guess easiest would be adding `class PetabImporterPysb(PetabImporter)` to `pypesto.petab.pysb_importer`. Shouldn't introduce too much new code, as most of `PetabImporter` can be used as is and less than a handful of functions need to be overridden.

### PR DESCRIPTION
**Pull request by dweindl**
Import for experimental PySB-based PEtab problems as supported by AMICI (https://github.com/ICB-DCM/AMICI/pull/1175). Closes #436 .

- [x] Wait for new PEtab release
- [x] Add optimization test based on some PEtab test suite case

### CODE REVIEW

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/pysb_importer.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5950037&bid=19503148)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/pysb_importer.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5950037&bid=19503148)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/pysb_importer.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5950037&bid=19503148)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/pysb_importer.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5950037&bid=19503148)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/pysb_importer.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5950037&bid=19503148)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/pysb_importer.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5950037&bid=19503148)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/pysb_importer.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5950037&bid=19503148)

**Review by FFroehlich — APPROVED** [review]

**Pull request merged**
