### PR TITLE
Disable FIM for models with parameter dependent sigma

### PR DESCRIPTION
**Pull request by FFroehlich**
Disable use of FIM for parameter dependent sigma until https://github.com/AMICI-dev/AMICI/issues/1335 is resolved

### CODE REVIEW

**Review by LeonardSchmiester — APPROVED** [review]
:+1:

**Review by yannikschaelte — APPROVED** [review]

**Comment by paulstapor** [comment]
Let's see whether https://github.com/AMICI-dev/AMICI/pull/1338 resolves it...

**Comment by FFroehlich** [comment]
> Let's see whether [AMICI-dev/AMICI#1338](https://github.com/AMICI-dev/AMICI/pull/1338) resolves it...
> I think you suggested the Schwen model to double check. Whic optimizer and setting would make the change in the FIM most apparent?

default options :)

**Comment by paulstapor** [comment]
> default options :)

Default options is L-BFGS-B... Does this really use a FIM? (running it atm)

**Comment by FFroehlich** [comment]
fixed in amici

**Pull request closed without merging**
