### PR TITLE
Speed-up import via lazy imports

### LINKED ISSUE #934: pypesto import is slow
`python -c "import pypesto"` takes 7s on my computer. 
`python -c "import scipy"` takes 0.5s on my computer. 

I think we should think more carefully about what is imported in `pypesto/__init__.py`

### PR DESCRIPTION
**Pull request by yannikschaelte**
fixes #934

### CODE REVIEW

**Comment by yannikschaelte** [comment]
Substantially faster now again (19s -> 3.5s, or 8s -> 1.3s). E.g. amici+petab not lazified yet, could be done but leaving for the moment as pypesto's use of those tools is quite strong.

**Review by dweindl — APPROVED** [review]
Much better, thanks. On-demand import of amici would be nice, but fine to merge as is. Definitely an improvement.

**Comment by yannikschaelte** [comment]
@dweindl now I also lazified amici+pypesto, in version (2) with local imports. does this seem fine to keep?

**Review by dweindl — APPROVED** [review]
:+1:

**Pull request merged**
