### PR TITLE
Push latest pyPESTO (develop) build as image with tag `latest` to docker.io

### PR DESCRIPTION
**Pull request by stephanmg**

### CODE REVIEW

**Comment by yannikschaelte** [comment]
Sounds good to me, would you use the docker image?

**Comment by stephanmg** [comment]
@yannikschaelte yes, I would use it, mostly in situations when run on a VM.

**Comment by stephanmg** [comment]
Rather should be deployed to Github registry not docker.

**Comment by stephanmg** [comment]
Pull and Run with Docker/Podman:
1. `docker pull ICB-DCM/pyPESTO:latest`
2. `docker run --rm username/image-name:tag python -c "import pypesto; print(pypesto.__version__")`

With singularity:
1. `singularity pull docker://ICB-DCM/pyPESTO:latest`
2. `singularity exec pyPESTO_latest.sif python -c "import pypesto; print(pypesto.__version__")`

**Review by vwiela — APPROVED** [review]

**Review by vwiela — APPROVED** [review]

**Comment by stephanmg** [comment]
Somebody with privileges for this repository needs to add two new secrets `DOCKER_TOKEN` and `DOCKER_USERNAME` to work.

**Pull request merged**
