### PR TITLE
[WIP] Import of benchmark collection models and data

### PR DESCRIPTION
**Pull request by dweindl**
Allow import of benchmark collection models and data from https://github.com/LoosC/Benchmark-Models/ (#23). Also some #68.

### CODE REVIEW

**Comment by yannikschaelte** [comment]
currently, sympy cannot be found. is that a requirement in amici? then it should be in the dependencies there, alternatively one can append it to https://github.com/ICB-DCM/pyPESTO/blob/master/.travis_pip_reqs.txt.

**Comment by dweindl** [comment]
@yannikschaelte It will be from AMICI 0.8.0 on

**Comment by yannikschaelte** [comment]
then let's require amici>=0.8.0 in https://github.com/ICB-DCM/pyPESTO/blob/master/.travis_pip_reqs.txt and setup.py

**Comment by dweindl** [comment]
as soon as the respective release is on pypi ;)

**Comment by yannikschaelte** [comment]
ah, right. then we will need to wait for that here? for the tests to work.

**Comment by yannikschaelte** [comment]
I still get for the Zheng model the following error (Boehm runs through though):
@dweindl Do you also get that error? System: Linux, everything pretty new / latest versions of all tools.

```model_Zheng_PNAS2012_dwdx.cpp: In function ‘void dwdx_model_Zheng_PNAS2012(amici::realtype*, amici::realtype, const realtype*, const realtype*, const realtype*, const realtype*, const realtype*)’:
model_Zheng_PNAS2012_dwdx.cpp:15:15: error: ‘inf’ was not declared in this scope
     dwdx[2] = inf.0*low;
               ^~~
model_Zheng_PNAS2012_dwdx.cpp:15:15: note: suggested alternative: ‘ynf’
     dwdx[2] = inf.0*low;
               ^~~
               ynf
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-4-cd0564b3768a> in <module>
      5                       measurement_file=measurement_filename,
      6                       model_output_dir=model_output_dir,
----> 7                       model_name=model_name)

~/pypesto/pypesto/objective/amici_objective.py in import_sbml_model(sbml_model_file, model_output_dir, model_name, measurement_file, condition_file, **kwargs)
    582                              constantParameters=constant_parameters,
    583                              sigmas=sigmas,
--> 584                              **kwargs
    585                              )

~/yenv/lib/python3.6/site-packages/amici/sbml_import.py in sbml2amici(self, modelName, output_dir, observables, constantParameters, sigmas, verbose, assume_pow_positivity, compiler)
    244         exporter.setPaths(output_dir)
    245         exporter.generateModelCode()
--> 246         exporter.compileModel()
    247 
    248     def processSBML(self, constantParameters=None):

~/yenv/lib/python3.6/site-packages/amici/ode_export.py in compileModel(self)
   1461 
   1462         """
-> 1463         self._compileCCode(compiler=self.compiler, verbose=self.verbose)
   1464 
   1465     def _prepareModelFolder(self):

~/yenv/lib/python3.6/site-packages/amici/ode_export.py in _compileCCode(self, verbose, compiler)
   1541                                     stdout=subprocess.PIPE,
   1542                                     stderr=subprocess.STDOUT,
-> 1543                                     check=True)
   1544         except subprocess.CalledProcessError as e:
   1545             print(e.output.decode('utf-8'))

/usr/lib/python3.6/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    416         if check and retcode:
    417             raise CalledProcessError(retcode, process.args,
--> 418                                      output=stdout, stderr=stderr)
    419     return CompletedProcess(process.args, retcode, stdout, stderr)
    420 

CalledProcessError: Command '['/home/yannik/yenv/bin/python3', '/home/yannik/pypesto/doc/example/tmp/model_model_Zheng_PNAS2012/setup.py', '--quiet', 'build_ext', '--build-lib=/home/yannik/pypesto/doc/example/tmp/model_model_Zheng_PNAS2012']' returned non-zero exit status 1.
```

**Comment by dweindl** [comment]
>     dwdx[2] = inf.0*low;

This is what symengine makes of `inflow` :roll_eyes: . Therefore, I guess you are not using the most recent AMICI version (v0.8.1)

**Comment by yannikschaelte** [comment]
Ay, seem to have updated before it was on pypi. Now it works, thanks. Note I changed the beer and boehm to uppercase in all files, now they should also work.

**Comment by yannikschaelte** [comment]
For temporary files, there exists a tmp sub directory under doc/example/, which is ignored by git. Maybe all compiled files can go there as well (instead of the deleteme folders)

**Comment by dweindl** [comment]
To be continued in [`feature_benchmark`](/ICB-DCM/pyPESTO/tree/feature_benchmark)

**Pull request closed without merging**
