### PR TITLE
Fix issue #723 (Consolidate different gradient checks)

### PR DESCRIPTION
**Pull request by stephanmg**
Address issue #723

### CODE REVIEW

**Comment by stephanmg** [comment]
Note, additional gradient check method converted to "private" method, as it is only a helper in a visualizing routine for gradient consistency (added on my fork and to be merged into pyPESTO as well).

**Review by yannikschaelte — CHANGES_REQUESTED** [review]
check_gradients_match_finite_differences is being used in tests

**Review by yannikschaelte — CHANGES_REQUESTED** [review]
petab tests are still failiing bc the function does no longer exist. As we agreed to remove this function, I suggest to rewrite those tests in terms of the other gradient check function.

Style tests are failiing -- consider installing pre-commit hooks and running `pre-commit run --all-files` to locally check before upload, see https://pypesto.readthedocs.io/en/latest/contribute.html#pre-commit-hooks

**Comment by stephanmg** [comment]
Should be corrected now, please review again. Thanks!

**Comment by PaulJonasJost** [comment]
@stephanmg What is the status here?

**Comment by stephanmg** [comment]
Closing this PR in favor of a new/clean PR to address the issues pointed out in issue #723.

**Pull request closed without merging**
