### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by yannikschaelte**
* Multi process parallelization
* Fix error for multiple conditions
* Fix documentation build
* Greatly extend visualization routines
* multiple minor things

Version 0.0.3 -> 0.0.4

### CODE REVIEW

**Comment by yannikschaelte** [comment]
didn't know squash-merging was possible. will look into that next time.

**Comment by paulstapor** [comment]
As we get PEtab import here: Please make sure, that we have an example for this, which documents the use... Maybe add a list of models, for which this is working, as a comment in a corresponding notebook.

**Comment by yannikschaelte** [comment]
good point. not completely clear yet if the files should be included in the examples folder, or if we just continue git-downloading the benchmark repo (which hopefully might also get smaller whence the old dependencies are removed), but we should definitely maintain a list of models for which pypesto works (i.e. everything from import, compilation to parameter estimation).

**Comment by paulstapor** [comment]
As this would go perfectly in line with #114, do we maybe want to wait for  #106 being merged?

**Comment by yannikschaelte** [comment]
currently, there were some updates to petab and amici which still need to be integrated (and both toolboxes updated as well). this is why the tests still fail. hopefully fixed in a few days.

**Pull request merged**
