### PR TITLE
Restrict fval magnitude in waterfall with order_by_id

### PR DESCRIPTION
**Pull request by m-philipps**
When using waterfall with `order_by_id=True` add a check for `fvals < 1e100` as is in place for `order_by_id=False`.

### CODE REVIEW

**Review by stephanmg — COMMENTED** [review]
1e100 is a reasonable threshold?

**Comment by m-philipps** [comment]
It's the same threshold that is used in the `order_by_id=False` case
https://github.com/ICB-DCM/pyPESTO/blob/462481eecb1a9fbf803a89bf11b59485a733c8f8/pypesto/visualize/waterfall.py#L133-L138

**Comment by stephanmg** [comment]
Changes looks fine, just wondering if should be made a parameter of the function. Opinions? @plakrisenko

**Review by stephanmg — APPROVED** [review]

**Comment by plakrisenko** [comment]
there is the `delete_nan_inf` function, maybe one could modify it a bit to also work in case `order_by_id=True`

**Review by plakrisenko — APPROVED** [review]

**Comment by plakrisenko** [comment]
> Changes looks fine, just wondering if should be made a parameter of the function. Opinions? @plakrisenko

It was introduced in https://github.com/ICB-DCM/pyPESTO/pull/999/files and is also used in parameters plot. 
One could introduce a constant, similar to https://github.com/ICB-DCM/pyPESTO/blob/develop/pypesto/C.py#L196

**Comment by stephanmg** [comment]
> > Changes looks fine, just wondering if should be made a parameter of the function. Opinions? @plakrisenko
> 
> It was introduced in https://github.com/ICB-DCM/pyPESTO/pull/999/files and is also used in parameters plot. One could introduce a constant, similar to https://github.com/ICB-DCM/pyPESTO/blob/develop/pypesto/C.py#L196

Thanks. I would go for a constant. Otherwise lgtm now!

**Comment by stephanmg** [comment]
Triggering a re-run of CI / base...

**Review by PaulJonasJost — APPROVED** [review]

**Pull request merged**
