### PR TITLE
Execute all notebooks / clear notebook output

### PR DESCRIPTION
**Pull request by Doresic**
All of the example notebooks are stored on GitHub with their output generated which is a lot of figures and text, taking up storage unnecessarily. I've removed the output, but I still need to check the notebook output is being generated for the online docs.

### CODE REVIEW

**Comment by Doresic** [comment]
I reduced the notebook output and run time by tweaking some small things like numbers of starts, rerunning, removing PEtab model compilation output, and added seeds for reproducability. Changes per notebook:
- `amici.py` -- verbose=False on model compilation, seed for reproducability, clear outputs
- `censored.ipynb` -- reduce n_starts 10 -> 3
- `getting_started.ipynb` -- n_starts 100 -> 10 (do we need more for a nicer waterfall plot?), added seed for reproducability, Fides verbose=logging.ERROR, create_problem verbose=False (TODO amici.swig_wrappers logging)
- `hierarchical.ipynb` -- change to only create_problem with verbose=False, set a seed for reproducibility
- `julia.py` -- set number of starts 100 --> 20, set seed for reproducability, samples 10000 -> 2000, clear outputs
- `nonlinear_monotone` -- verbose=False on model compilation
- `ordinal` -- verbose=False on model compilation
- `petab_import` -- verbose=False on model compilation
- `sampler_study` -- verbose=False on model compilation
- `store` -- verbose=False on model compilation, fides verbose ERROR
- `synthetic_data` -- n_starts 100 -> 20, verbose=False on model compilation
- `workflow_comparison` -- verbose=False on model compilation, n_starts 25 - 10

**Comment by Doresic** [comment]
The docs test is very slow at this point:
```
reading sources... [ 56%] example
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Warning:  Could not parse YAML metadata at line 5 column 1: not an object
Warning:  Could not parse YAML metadata at line 15 column 1: not an object
reading sources... [ 58%] example/amici
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
reading sources... [ 60%] example/censored
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

I'm not sure what is the issue with these `frozen modules`. As much as I could find out it did have something to do with Jupyter and python 3.11. Searching for a solution to speed up the example build...

**Comment by dweindl** [comment]
> I'm not sure what is the issue with these `frozen modules`. As much as I could find out it did have something to do with Jupyter and python 3.11. Searching for a solution to speed up the example build...

Thanks for the cleanup so far.

Don't worry about this message, not relevant here. I silenced it.


Further opportunity for optimization:

```
result = optimize.minimize(problem=problem, 
                           optimizer=optimizer_scipy_lbfgsb,
                           engine=engine,
                           n_starts=100)
```
... we probably can reduce n_starts there.

**Comment by Doresic** [comment]
Even when running locally (`tox -e doc`), reading sources is taking too long. It already starts at the `conversion_reaction.ipynb` notebook.
I think it might have something to do with this: when I run the notebook alone with python 3.10 it all runs nicely. If I run it with 3.11 the first optimization starts printing a lot of these errors:
image
So much so, that the whole notebook freezes.

**Comment by Doresic** [comment]
> > I'm not sure what is the issue with these `frozen modules`. As much as I could find out it did have something to do with Jupyter and python 3.11. Searching for a solution to speed up the example build...
> 
> Thanks for the cleanup so far.
> 
> Don't worry about this message, not relevant here. I silenced it.
> 
> Further opportunity for optimization:
> 
> getting_started.ipynb:
> 
> ```
> result = optimize.minimize(problem=problem, 
>                            optimizer=optimizer_scipy_lbfgsb,
>                            engine=engine,
>                            n_starts=100)
> ```
> 
> ... we probably can reduce n_starts there.
> 
> same notebook: computing profiles for 3 parameter should be sufficient, we don't need all.

If this is the point I think it is, I left it as 100 startpoints so the global optimum found is nice enough to have nice profiles. It doesn't take that long to run (relative to the profiling). But running 3 profiles is definitely better.

**Comment by dweindl** [comment]
> a lot of these errors:

see also https://github.com/ICB-DCM/pyPESTO/issues/1159

**Comment by dweindl** [comment]
To speed things up:
* I think we can use a faster model in getting_started, not sure we need anything ODE/PEtab-based in there. we can just reference the other example.
* I don't think we need to show profiles and sampling using 5 different types of Objectives. Quite some examples can be reduced. e.g., https://pypesto.readthedocs.io/en/latest/example/conversion_reaction.html seems to be rather redundant and could be removed after moving maybe the ensemble part somewhere else. maybe the construction of the objective can be moved to the amici notebook if not already there. also for the julia notebook, i think it sufficient to show optimization, the rest should be straight-forward.

**Comment by Doresic** [comment]
Merging the `PetabImporter` verbose change in #1269

**Comment by Doresic** [comment]
There still seems to be too little time for the readthedocs build. It stops at 
```
[2Kreading sources... [ 84%] example/store

Command killed due to timeout or excessive memory consumption
```

Will take a look at the rest of the notebooks, specifically the sampling ones, I have a feeling they are taking too long to build.

**Comment by Doresic** [comment]
New changes:
- `sampling_diagnostics` -- n_samples 10000 -> 1000 on both sampling
- `sampler_study` -- n_samples 1e4 -> 1e3 where not necessary to have an extremely good sampling result, add seed for reproducibility (to have a consistently low burn-in to be able to have only 1e3 samples).

**Review by dilpath — APPROVED** [review]
:+1:

**Review by stephanmg — APPROVED** [review]
Thanks for cleaning this up.

**Review by dweindl — APPROVED** [review]
:+1:

**Review by FFroehlich — APPROVED** [review]

**Pull request merged**
