### PR TITLE
Mark test_preeq_guesses and test_optimization as flaky

### PR DESCRIPTION
**Pull request by dweindl**

### CODE REVIEW

**Review by yannikschaelte — APPROVED** [review]

**Review by yannikschaelte — APPROVED** [review]
5 feels a bit much, in that case one may want to investiagte causes ... but ok surely

**Comment by dweindl** [comment]
> 5 feels a bit much, in that case one may want to investiagte causes ... but ok surely

How much feels right? :)

**Comment by yannikschaelte** [comment]
> > 5 feels a bit much, in that case one may want to investiagte causes ... but ok surely
> 
> How much feels right? :)

three and three quarters?

**Comment by jvanhoefer** [comment]
@dweindl @yannikschaelte What is the status here? Is this ready to merge? :)

**Comment by yannikschaelte** [comment]
sí

**Pull request merged**
