### PR TITLE
prepare release 0.2.17

### PR DESCRIPTION
**Pull request by PaulJonasJost**

### CODE REVIEW

**Review by dweindl — APPROVED** [review]
:+1:

**Review by yannikschaelte — CHANGES_REQUESTED** [review]
should be 0.2.17 in changelog

**Comment by yannikschaelte** [comment]
For 0.3 we'd also need a full list of all the major changes (mostly feature addidions) that occurred in 0.2.xy

**Comment by PaulJonasJost** [comment]
> For 0.3 we'd also need a full list of all the major changes (mostly feature addidions) that occurred in 0.2.xy

@yannikschaelte changed it to 0.2.17 for now

**Review by yannikschaelte — APPROVED** [review]
perfect, thanks!

**Pull request merged**
