### PR TITLE
release v0.2.2

### PR DESCRIPTION
**Pull request by jvanhoefer**

### CODE REVIEW

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- test/test_problem.py  4
- pypesto/profile/profile.py  1
- pypesto/visualize/optimizer_convergence.py  4
- test/test_optimize.py  1
- pypesto/objective/amici_util.py  2
         

Complexity decreasing per file
==============================
+ pypesto/profile/approximate.py  -1
+ pypesto/profile/util.py  -1
+ pypesto/problem.py  -1
+ pypesto/objective/amici_calculator.py  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=6284642&bid=20450016)

**Review by yannikschaelte — APPROVED** [review]
The history looks screwed up again, not sure why. But should be fine.

**Comment by yannikschaelte** [comment]
edit: No, conflict between master and develop, will resolve that separately.

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/objective/amici_util.py  2
- test/test_problem.py  4
- test/test_optimize.py  1
- pypesto/visualize/optimizer_convergence.py  4
- pypesto/profile/profile.py  1
         

Complexity decreasing per file
==============================
+ pypesto/objective/amici_calculator.py  -6
+ pypesto/profile/approximate.py  -1
+ pypesto/problem.py  -1
+ pypesto/profile/util.py  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=6284642&bid=20450016)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/visualize/optimizer_convergence.py  4
- test/test_optimize.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=6284642&bid=20450016)

**Pull request merged**
