### PR TITLE
Fix re 'DeprecationWarning: Flags not at the start of the expression'

### LINKED ISSUE #61: Deprecation warning Regular expression
should be easy to fix, is just annoying.
```
/.../pypesto/pypesto/optimize/optimizer.py:349: DeprecationWarning: Flags not at the start of the expression '^(?i)(ls_)'
  return re.match(r'^(?i)(ls_)', self.method)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

### PR DESCRIPTION
**Pull request by dweindl**
Fixes #61

### CODE REVIEW

**Comment by dweindl** [comment]
The actual issue is fixed. 

Who is responsible for 
```
1.16s$ python3 -m flake8 --ignore=F401 --exclude=build,doc,example
./pypesto/objective/history.py:209:25: W504 line break after binary operator
./pypesto/objective/objective.py:159:46: E252 missing whitespace around parameter equals
./pypesto/objective/objective.py:159:47: E252 missing whitespace around parameter equals
./pypesto/objective/objective.py:608:21: W504 line break after binary operator
./pypesto/objective/objective.py:609:21: W504 line break after binary operator
./pypesto/objective/objective.py:610:21: W504 line break after binary operator
./pypesto/objective/objective.py:611:21: W504 line break after binary operator
./pypesto/objective/objective.py:612:21: W504 line break after binary operator
./pypesto/objective/objective.py:613:21: W504 line break after binary operator
./pypesto/objective/objective.py:614:21: W504 line break after binary operator
The command "python3 -m flake8 --ignore=F401 --exclude=build,doc,example" exited with 1.
```

**Comment by FFroehlich** [comment]
I think those are due to a flake update that flags new problem.
I believe I fixed all of them in my latest PR.

**Comment by dweindl** [comment]
Thx. Will wait for #59 then.

**Comment by yannikschaelte** [comment]
Yes, I think those cropped up only recently.

**Pull request merged**
