### PR TITLE
Separate AMICI call

### PR DESCRIPTION
**Pull request by yannikschaelte**
Move AMICI call to a separate function. This will allow to plug in a hierarchical formulation.

### CODE REVIEW

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/petab/importer.py  5
- pypesto/objective/amici_calculator.py  10
- pypesto/objective/amici_util.py  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5343793&bid=17495536)

**Comment by FFroehlich** [comment]
will wait until #274 is merged, looks like some remaining redundancy.

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/objective/amici_calculator.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5343793&bid=17495536)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/objective/amici_calculator.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5343793&bid=17495536)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/objective/amici_calculator.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5343793&bid=17495536)

**Comment by dweindl** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pypesto/objective/amici_calculator.py  10
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dweindl/pyPESTO/pullRequest?prid=5343793&bid=17495536)

**Pull request merged**
