### PR TITLE
Fix hdf5 result mismatch

### LINKED ISSUE #743: Flaky test_result_from_hdf5_history?
Fails here https://github.com/ICB-DCM/pyPESTO/runs/3893112578?check_suite_focus=true

I don't think that's related to that commit.

```
________________________ test_result_from_hdf5_history _________________________

    def test_result_from_hdf5_history():
        problem = create_petab_problem()
        with tempfile.TemporaryDirectory(dir=".") as tmpdirname:
            _, fn = tempfile.mkstemp(".hdf5", dir=f"{tmpdirname}")
    
            history_options_hdf5 = pypesto.HistoryOptions(trace_record=True,
                                                          storage_file=fn)
            # optimize with history saved to hdf5
            result = pypesto.optimize.minimize(
                problem=problem, n_starts=1,
                history_options=history_options_hdf5)
    
            result_from_hdf5 = optimization_result_from_history(fn)
    
            # Currently 'exitflag', 'time' and 'message' are not loaded.
            arguments = [ID, X, FVAL, GRAD, HESS, RES, SRES,
                         N_FVAL, N_GRAD, N_HESS, N_RES, N_SRES, X0, FVAL0]
            for key in arguments:
                if result.optimize_result.list[0][key] is None:
                    assert result_from_hdf5.optimize_result.list[0][key] is None
                elif isinstance(result.optimize_result.list[0][key], np.ndarray):
>                   np.testing.assert_almost_equal(
                        result.optimize_result.list[0][key],
                        result_from_hdf5.optimize_result.list[0][key]
                    )
E                   AssertionError: 
E                   Arrays are not almost equal to 7 decimals
E                   
E                   Mismatched elements: 2 / 2 (100%)
E                   Max absolute difference: 0.0001968
E                   Max relative difference: 0.00014251
E                    x: array([-0.915745 , -7.9470828])
E                    y: array([-0.9156145, -7.946886 ])

test/base/test_store.py:424: AssertionError
```

### PR DESCRIPTION
**Pull request by PaulJonasJost**
should fix #743. Ran the `test_result_from_hdf5_history` test 1000 times and it was successful every time.

Potentially we could remove the `_update` function of `OptimizerHistory`?

### CODE REVIEW

**Comment by yannikschaelte** [comment]
Sure this would remove any ambiguity by always taking results from the trace. But is it clear why this happens in the first place?

**Comment by PaulJonasJost** [comment]
> Sure this would remove any ambiguity by always taking results from the trace. But is it clear why this happens in the first place?

Do not quote me on it, but I think it has to do with the fact that in line 1459, the algorithm goes in reversed order while in the update function he goes from the other side.

**Comment by dweindl** [comment]
> > Sure this would remove any ambiguity by always taking results from the trace. But is it clear why this happens in the first place?
> 
> Do not quote me on it, but I think it has to do with the fact that in line 1459, the algorithm goes in reversed order while in the update function he goes from the other side.

Not sure I understand the original problem. Could you elaborate?

Also, the default tolerances implicitly used in `allclose` (`rtol=1e-05, atol=1e-08`) in the referenced line seem very loose to me.

**Comment by dweindl** [comment]
Sorry for the delay, and thanks for the explanation.

> So in the [_update_vals()](https://github.com/ICB-DCM/pyPESTO/blob/46eb703c8fc21d1fcebc9dd1b2076bf72880355d/pypesto/objective/history.py#L1402) function of the Optimizer_History, we assign the grad_min, hess_min, res_min, sres_min in a way, that they get assigned if they are not yet assigned and the current updated point is close to the minimal point.

I don't quite understand why they are only assigned if they are `None` (@yannikschaelte ?). Could that be the underlying problem? 
https://github.com/ICB-DCM/pyPESTO/blob/46eb703c8fc21d1fcebc9dd1b2076bf72880355d/pypesto/objective/history.py#L1403-L1409

**Comment by yannikschaelte** [comment]
closed in favor of #902

**Pull request closed without merging**
