### PR TITLE
Calling prior in sampling with fixed parameters does not work

### PR DESCRIPTION
**Pull request by arrjon**
The `NegLogParameterPriors` objective does not properly account for fixed parameters when invoked during sampling. When it's integrated into the `AggregatedObjective`, optimization functions correctly; however, issues arise during sampling because `call_unprocessed` is triggered with the reduced parameter vector, causing a failure.

Maybe there is a better way to fix this, as I just updated the call of `neglogprior`, but I feel this might break stuff during optimzation.

### CODE REVIEW

**Comment by arrjon** [comment]
I reverted the inital fix since I found a better solution. If you now call `problem.x_priors` it behaves exactly as `problem.objective`, which is the behaviour I would expect.

**Review by dilpath — APPROVED** [review]
Fine for me for now :+1:

I imagine this will be obsolete if #1325 is resolved by implementing objective type flags.

**Review by vwiela — APPROVED** [review]
Thanks for spotting. 

Think this is a good fix to it.

**Comment by arrjon** [comment]
After discussion, @PaulJonasJost and I removed the deepcopy of the class. Otherwise, copying the prior does not work. This happens in the parallel tempering sampler, when the prior is copied to the different chains.

**Pull request merged**
